export const sliderItems = [
  {
    id: 1,
    img: "https://i.ibb.co/2660cv2/summer-photo.png",
    title: "SOMETHING SALE",
    desc: "SOMETHING DESCRIBING THE SALE!!! GRAB YOUR CHANCE NOW!!!.",
    bg: "fcf1ed",
  },
  {
    id: 2,
    img: "https://i.ibb.co/DG69bQ4/2.png",
    title: "NEW ARRIVALS",
    desc: "SOMETHING DESCRIBING THE NEW ARRIVAL!!! GRAB YOUR CHANCE NOW!!!.",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://i.ibb.co/cXFnLLV/3.png",
    title: "MOST BUYED",
    desc: "SOMETHING DESCRIBING THE MOST BUYED PRODUCTS!!! GRAB YOUR CHANCE NOW!!!.",
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://i.postimg.cc/13qyhGjb/shirt.jpg",
    title: "SHIRT STYLE",
    category: "shirt",
  },
  {
    id: 2,
    img: "https://i.postimg.cc/yNJk2Cyy/shoes.jpg",
    title: "SHOES LOVE",
    category: "shoes",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1457983/pexels-photo-1457983.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "LIGHT JACKETS",
    category: "jackets",
  },
];

export const popularProducts = [
  {
    id: 11242113114,
    productName: "Jake Guitar Vintage Crusher Tee",
    price: 499,
    color: ["lightPink", "green", "gray"],
    size: ["S", "M", "XL"],
    category: ["shirt", "men", "man", "shirts"],
    quantity: 0,
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
  },
  {
    id: 22312113114,
    productName: "Jacket Demin",
    price: 999,
    color: ["blue", "black"],
    size: ["XS", "S", "M", "L"],
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    category: ["jacket", "jackets", "men", "man"],
    quantity: 0,
    img: "https://www.freepnglogos.com/uploads/jacket-png/jacket-denim-solutions-website-launching-program-denim-solutions-ltd-24.png",
  },
  {
    id: 31242113114,
    productName: "Prada Shirt",
    price: 2999,
    color: [],
    size: ["XS", "S", "M", "L", "XL"],
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    category: ["shirt", "shirts", "men", "man"],
    quantity: 0,
    img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
  },
  {
    id: 41242113114,
    productName: "Bruda Style Dress",
    price: 2999,
    size: ["XS", "S", "M", "L", "XL", "XXL"],
    color: ["white", "black"],
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    category: ["dress", "women", "woman"],
    quantity: 0,
    img: "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
  },
  {
    id: 51242113114,
    productName: "Tote Bag: SAVE EARTH",
    price: 200,
    color: ["white"],
    size: ["1"],
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    category: ["accessories", "accessory", "bag", "tote", "bags"],
    quantity: 0,
    img: "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
  },
  {
    id: 61242113114,
    productName: "Life is good cap",
    price: 300,
    color: ["gray"],
    size: ["1"],
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    category: ["accessories", "men", "man", "cap"],
    quantity: 0,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
  },
  {
    id: 71242113114,
    productName: "Louis Vuitton Boots",
    price: 3999,
    color: ["maroon", "black"],
    size: ["6", "7", "8", "9"],
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    category: ["shoe", "shoes", "women", "woman"],
    quantity: 0,
    img: "https://www.freepnglogos.com/uploads/women-shoes-png/clipart-women-shoes-transparent-background-collection-28.png",
  },
  {
    id: 81242113114,
    productName: "Women Jacket",
    price: 1999,
    color: ["burlywood", "red"],
    size: ["XS", "S", "M", "L", "XL", "XXL"],
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    category: ["jacket", "jackets", "women", "woman"],
    quantity: 0,
    img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
  },
];
